## 想要假設簡單的商品與原料的問題

先輸入數個原料，以及各個原料的(限有最大)數量

再輸入商品以及生產一單位商品所需的原料數量

即可出現類似矩陣的 array，表達生產產品所需的原料數量


In [41]:
## 詢問 equation

import numpy as np 

print('')
resourceDict = {}
# 限二維
# while True:

def getLimit(resourceDict):
    resource = input('請輸入原料')
    resourceAmount = input(f'請輸入{resource}的限有數量')
    resourceDict[resource] = float(resourceAmount)
    return resourceDict
    
    
productList = []
    
def getEquation(resourceDict, productList):
    
    productName = input('請輸入商品名稱: ')
    productList.append(productName)
    for resource in resourceDict:
        require = input(f'生產一單位{productName}需要幾單位的{resource}? ')
        try:
            requireArray = requireArray
            requireArray = np.append(requireArray, [[float(require)]], axis=0)
        except:
            requireArray = np.array([[float(require)]])
    
    return requireArray
    


    
inputResource = True
while inputResource:
    inputResource = input('是否輸入原料資訊? (y/n) ')
    if inputResource == 'y':
        resourceDict = getLimit(resourceDict)
    else:
        inputResource = False

inputProduct = True  

while inputProduct:
    inputProduct = input('是否輸入商品資訊? (y/n)')
    if inputProduct == 'y':
        require = getEquation(resourceDict, productList)
        try:
            # allRequireArray
            allRequireArray = np.append(allRequireArray, require, axis=1)
        except:
            allRequireArray = np.array(require)
    else:
        inputProduct = False
        
print('\n')

print(allRequireArray)

print('\n dot \n')

for p in productList:
    try:
        pArray = np.append(pArray, [[p]], axis=0)
    except:
        pArray = np.array([[p]])
    
print(pArray)

print('\n = \n')
for resource in resourceDict:
    try:
        rAmount = np.append(rAmount, [[resourceDict[resource]]], axis=0)
    except:
        rAmount = np.array([[resourceDict[resource]]]) 
print(rAmount)
    
    
del pArray
del rAmount
# del requireArray
del allRequireArray


是否輸入原料資訊? (y/n) y
請輸入原料r1
請輸入r1的限有數量10
是否輸入原料資訊? (y/n) y
請輸入原料r2
請輸入r2的限有數量20
是否輸入原料資訊? (y/n) y
請輸入原料r3
請輸入r3的限有數量30
是否輸入原料資訊? (y/n) n
是否輸入商品資訊? (y/n)y
請輸入商品名稱: p1
生產一單位p1需要幾單位的r1? 1
生產一單位p1需要幾單位的r2? 2
生產一單位p1需要幾單位的r3? 3
是否輸入商品資訊? (y/n)y
請輸入商品名稱: p2
生產一單位p2需要幾單位的r1? 4
生產一單位p2需要幾單位的r2? 5
生產一單位p2需要幾單位的r3? 6
是否輸入商品資訊? (y/n)y
請輸入商品名稱: p3
生產一單位p3需要幾單位的r1? 7
生產一單位p3需要幾單位的r2? 8
生產一單位p3需要幾單位的r3? 9
是否輸入商品資訊? (y/n)y
請輸入商品名稱: p4
生產一單位p4需要幾單位的r1? 10
生產一單位p4需要幾單位的r2? 11
生產一單位p4需要幾單位的r3? 12
是否輸入商品資訊? (y/n)n


[[ 1.  4.  7. 10.]
 [ 2.  5.  8. 11.]
 [ 3.  6.  9. 12.]]

 dot 

[['p1']
 ['p2']
 ['p3']
 ['p4']]

 = 

[[10.]
 [20.]
 [30.]]


In [5]:
import numpy as np

resourceDict = {}
productList = []

def getLimit(resourceDict):
    resource = input('請輸入原料')
    resourceAmount = input(f'請輸入{resource}的限有數量')
    resourceDict[resource] = float(resourceAmount)
    return resourceDict

    
def getEquation(resourceDict, productList):
    
    productName = input('請輸入商品名稱: ')
    productList.append(productName)
    for resource in resourceDict:
        require = input(f'生產一單位{productName}需要幾單位的{resource}? ')
        try:
            requireArray = requireArray
            requireArray = np.append(requireArray, [[float(require)]], axis=0)
        except:
            requireArray = np.array([[float(require)]])
    
    return requireArray

inputResource = True
while inputResource:
    inputResource = input('是否輸入原料資訊? (y/n) ')
    if inputResource == 'y':
        resourceDict = getLimit(resourceDict)
    else:
        inputResource = False

inputProduct = True  

while inputProduct:
    inputProduct = input('是否輸入商品資訊? (y/n)')
    if inputProduct == 'y':
        require = getEquation(resourceDict, productList)
        try:
            # allRequireArray
            allRequireArray = np.append(allRequireArray, require, axis=1)
        except:
            allRequireArray = np.array(require)
    else:
        inputProduct = False
        
#from ipywidgets import interact



for p in productList:
    try:
        pArray = np.append(pArray, [[int(input(f'{p}要生產幾個? '))]], axis=0)
    except:
        pArray = np.array([[int(input(f'{p}要生產幾個? '))]])

print(allRequireArray)
print('\t')
print('內積')
print(pArray)
print('\n')
        
resources = allRequireArray@pArray
print(resources)

for resource in resourceDict:
    try:
        rAmount = np.append(rAmount, [[resourceDict[resource]]], axis=0)
    except:
        rAmount = np.array([[resourceDict[resource]]]) 
        
        

print('\n實際原料有\n', rAmount)
del pArray
del rAmount
# del requireArray
del allRequireArray

是否輸入原料資訊? (y/n) y
請輸入原料r1
請輸入r1的限有數量100
是否輸入原料資訊? (y/n) y
請輸入原料r2
請輸入r2的限有數量150
是否輸入原料資訊? (y/n) n
是否輸入商品資訊? (y/n)y
請輸入商品名稱: p1
生產一單位p1需要幾單位的r1? 2
生產一單位p1需要幾單位的r2? 4
是否輸入商品資訊? (y/n)y
請輸入商品名稱: p2
生產一單位p2需要幾單位的r1? 8
生產一單位p2需要幾單位的r2? 1
是否輸入商品資訊? (y/n)y
請輸入商品名稱: p3
生產一單位p3需要幾單位的r1? 6
生產一單位p3需要幾單位的r2? 3
是否輸入商品資訊? (y/n)n
p1要生產幾個? 9
p2要生產幾個? 6
p3要生產幾個? 5
[[2. 8. 6.]
 [4. 1. 3.]]
	
內積
[[9]
 [6]
 [5]]


[[96.]
 [57.]]

實際原料有
 [[100.]
 [150.]]
